name: frontend
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/forest.png
    - assets/images/google_icon.png
    - assets/images/boy.svg
    - assets/images/girl.svg
    - assets/images/Star.svg